version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      # Going to start with a high interval, and then tone it back
      interval: daily
      timezone: America/Los_Angeles
      time: "15:30"
    reviewers:
      - "@getsentry/owners-js-build"
    ignore:
      # Babel updates all really should happen in unison, so let's keep these
      # ignored for now and manually handle it
      #
      # XXX(epurkhiser): Explicitly don't ignore core so we can be reminded to
      # upgrade all of them.
      #
      # - dependency-name: "@babel/core"
      - dependency-name: "@babel/plugin-proposal-decorators"
      - dependency-name: "@babel/plugin-transform-react-jsx"
      - dependency-name: "@babel/plugin-transform-react-jsx-source"
      - dependency-name: "@babel/plugin-transform-runtime"
      - dependency-name: "@babel/preset-env"
      - dependency-name: "@babel/preset-react"
      - dependency-name: "@babel/preset-typescript"
      - dependency-name: "@babel/runtime"

      # We ignore everything that hasn't yet been upgrade, this way we will
      # only get the _freshest_ of new packages to consider upgrading
      - dependency-name: "@sentry/release-parser"
      - dependency-name: "@size-limit/preset-small-lib"
      - dependency-name: "@types/echarts"
      - dependency-name: "@types/marked"
      - dependency-name: "@wojtekmaj/enzyme-adapter-react-17"
      - dependency-name: "clean-webpack-plugin"
      - dependency-name: "compression-webpack-plugin"
      - dependency-name: "copy-text-to-clipboard"
      - dependency-name: "create-react-class"
      - dependency-name: "dotenv-webpack"
      - dependency-name: "echarts"
      - dependency-name: "echarts-for-react"
      - dependency-name: "eslint"
      - dependency-name: "eslint-plugin-simple-import-sort"
      - dependency-name: "fuse.js"
      - dependency-name: "gettext-parser"
      - dependency-name: "less"
      - dependency-name: "less-loader"
      - dependency-name: "marked"
      - dependency-name: "mini-css-extract-plugin"
      - dependency-name: "react-date-range"
      - dependency-name: "react-lazyload"
      - dependency-name: "react-refresh"
      - dependency-name: "rrweb"
      - dependency-name: "rrweb-player"
      - dependency-name: "size-limit"
      - dependency-name: "terser-webpack-plugin"
      - dependency-name: "u2f-api"

      # Jest will be upgraded soon in https://github.com/getsentry/sentry/pull/26393
      - dependency-name: "jest"
      - dependency-name: "jest-circus"
      - dependency-name: "jest-junit"
      - dependency-name: "babel-jest"
      - dependency-name: "@visual-snapshot/jest"

      # We use 3 javascript parts of bootstrap. All of the less styles have
      # been vendored already
      - dependency-name: "bootstrap"

      # Hopefully we can get rid of this somewhat soon.. but for now bootstrap
      # and the app still needs it in a few places...
      - dependency-name: "jquery"
      - dependency-name: "@types/jquery"

      # Going from 1.x -> 2.x is a pretty big refactoring in terms of how
      # popper is used.
      - dependency-name: "react-popper"

      # In 4.x the values provided to onChange have changed (for the better).
      # But this will require some refactoring. This holds part of our app on
      # emotion 10.
      - dependency-name: "react-select"
      - dependency-name: "@types/react-select"

      # We're stuck on react-router 3.x until we figure out how to use 5.x
      - dependency-name: "react-router"
      - dependency-name: "@types/react-router"

      # We're stuck on very old reflux as we'll likely deprecate this
      # sometime in the near-term for something more modern like
      # react-contexts, recoil, mobx, etc
      - dependency-name: "reflux"
      - dependency-name: "@types/reflux"
